language: node_js
sudo: false
node_js:
  - "5"
script:
  - npm run test
  - npm run build
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
